source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'

gem 'opal', github: 'youchan/opal', branch: 'marshal-dump-bignum'
gem 'opal-sprockets', github: 'opal/opal-sprockets'

gem 'rake'
gem 'sass'
